# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/sam/git_workspace/floating-point-axi-lite-slave-interface-/axilite_slave_fgravity/axilite_slave_fgravity.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
# IP: The module: 'design_1_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sam/git_workspace/floating-point-axi-lite-slave-interface-/axilite_slave_fgravity/axilite_slave_fgravity.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sam/git_workspace/floating-point-axi-lite-slave-interface-/axilite_slave_fgravity/axilite_slave_fgravity.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sam/git_workspace/floating-point-axi-lite-slave-interface-/axilite_slave_fgravity/axilite_slave_fgravity.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/sam/git_workspace/floating-point-axi-lite-slave-interface-/axilite_slave_fgravity/axilite_slave_fgravity.srcs/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xci
# IP: The module: 'design_1_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/sam/git_workspace/floating-point-axi-lite-slave-interface-/axilite_slave_fgravity/axilite_slave_fgravity.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sam/git_workspace/floating-point-axi-lite-slave-interface-/axilite_slave_fgravity/axilite_slave_fgravity.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/sam/git_workspace/floating-point-axi-lite-slave-interface-/axilite_slave_fgravity/axilite_slave_fgravity.gen/sources_1/bd/design_1/ip/design_1_rst_ps7_0_100M_0/design_1_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
